theme: jekyll-theme-architect
title: Muse'zik
description: MuseScore, pour jouer et progresser
google_analytics: 182952059

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
